ShoppingChart1/ShoppingChart1/Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShoppingChart1.Models
{
    public class Item
    {
        public Product Product { get; set; }
        public int Quantity { get; set; }

    }
}

ShoppingChart1/ShoppingChart1/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShoppingChart1.Models
{
    public class Product
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public string Photo { get; set; }


    }
}

ShoppingChart1/ShoppingChart1/Models/ProductModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShoppingChart1.Models
{
    public class ProductModel
    {
        private List<Product> products;
        public ProductModel()
        {
            this.products = new List<Product>()
            {
                new Product()
                {
                    Id="01",
                    Name="Cipele na stiklu",
                    Price=1000,
                    Photo="cipele-na-stiklu-5010-crvene_11290.jpg"

                },
                new Product()
                {
                    Id="02",
                    Name="Elegantne muske cipele",
                    Price=1500,
                    Photo="elegantne-muske-cipele-2062-29f-braon_486968.jpg"
                },
                new Product()
                {
                    Id="03",
                    Name=" Muski sorc",
                    Price=2000,
                    Photo="Muski sorc.jpg"
                },
                new Product()
                {
                    Id="04",
                    Name="Patike muske bele",
                    Price=1800,
                    Photo="Patike muske bele.jpg"
                },
                new Product()
                {
                    Id="05",
                    Name="Zenska torba i haljina",
                    Price=2500,
                    Photo="Zenska torba i haljina.jpg"
                },
                new Product()
                {
                    Id="06",
                    Name="Zenske helanke",
                    Price=2800,
                    Photo="Zenske helanke.jpg"
                },
                new Product()
                {
                    Id="07",
                    Name="Cipele na stiklu crne",
                    Price=3000,
                    Photo="cipele-na-stiklu-5010-crne_11272.jpg"
                },
                 new Product()
                {
                    Id="08",
                    Name="Decija zenska jakna",
                    Price=2500,
                    Photo="Decija zenska jakna.jpg"
                },
                  new Product()
                {
                    Id="09",
                    Name="Muske patike braon",
                    Price=2500,
                    Photo="Muske patike braon.jpg"
                },
                   new Product()
                {
                    Id="10",
                    Name="Plavi duks",
                    Price=1800,
                    Photo="Plavi duks.jpg"
                }

            };
        }
        public List<Product> findAll()
        {
            return this.products;
        }
        public Product find(string id)
        {
            return this.products.Single(products => products.Id.Equals(id));
        }
    }
}

ShoppingChart1/ShoppingChart1/Controllers/CartController.cs
using ShoppingChart1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoppingChart1.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {

            return View();
        }
        public ActionResult Buy(string id)
        {
            ProductModel productmodel = new ProductModel();
            if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item
                {
                    Product = productmodel.find(id),
                    Quantity = 1
                });
                Session["cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>) Session["cart"];
                int index = isExist(id);
                if (index!= -1)
                {
                    cart[index].Quantity++;

                }
                else
                {
                    cart.Add(new Item { Product = productmodel.find(id), Quantity = 1 });
                }
                Session["cart"] = cart;

            }
            return RedirectToAction("Index");
        }
        public ActionResult Remove(string id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            int index = isExist(id);
            cart.RemoveAt(index);
            Session["cart"] = cart;

            return RedirectToAction("Index");
        }

        private int isExist(string id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for(int i = 0; i < cart.Count; i++)
            
                if (cart[i].Product.Id.Equals(id))
                
                    return i;

                
                return -1;
                   
            
        }
    }
}

ShoppingChart1/ShoppingChart1/Controllers/ProductController.cs
using ShoppingChart1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace ShoppingChart1.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index(int? page)
        {
            ProductModel productModel = new ProductModel();

            ViewBag.products = productModel.findAll();
            
            return View();
        }
    }
}

ShoppingChart1/ShoppingChart1/Views/Cart/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@using ShoppingChart1.Models

<h2>Index</h2>
<html>
<head>
    <meta name="viewport" content="width=device-width">
    <title>Cart</title>
    <link rel="stylesheet" href="Site.css"/>
</head>
<body class="class1">
    <h3>Cart Page</h3>
    <table cellpadding="2" cellspacing="2" border="1">
        <tr id="id1">
            <th>Option</th>
            <th>Id</th>
            <th>Name</th>
            <th>Photo</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Sub Total</th>
        </tr>
        @foreach (Item item in (List<Item>)Session["cart"])
        {
            <tr>
                <td><a href="@Url.Action("Remove","Cart", new { id=item.Product.Id})">Remove</a> </td>
                <td>@item.Product.Id</td>
                <td>@item.Product.Name</td>
                <td><img src="~/Content/Images/@item.Product.Photo" width="60" /></td>
                <td>@item.Product.Price</td>
                <td>@item.Quantity</td>
                <td>@(item.Product.Price*item.Quantity)</td>


            </tr>
        }
        <tr>
            <td align="right" colspan="6">Sum</td>
            <td>
                @{
                    List<Item> cart = (List<Item>)Session["cart"];
                    var total = cart.Sum(item => item.Product.Price * item.Quantity);
                }
                @total
            </td>
        </tr>

    </table>
    <br />
    <a href="@Url.Action("Index","Product")">Continue Shopping</a>

</body>

</html>

ShoppingChart1/ShoppingChart1/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@using ShoppingChart1.Models

<html>
<head>
    <meta name="viewport" content="width=device-width" >
    <title>Index</title>
    <link rel="stylesheet" href="Site.css"/>
</head>
<body class="class2">
    <h3>Product List</h3>
    <table cellpadding="2" cellspacing="2" border="1">
        <tr id="id2">

            <th>Id</th>
            <th>Name</th>
            <th>Photo</th>
            <th>Price</th>
            <th>Buy</th>

        </tr>
        @foreach (Product product in ViewBag.products)
        {
            <tr>
                <td>@product.Id</td>
                <td>@product.Name</td>
                <td><img src="~/Content/Images/@product.Photo" width="60" /></td>


                <td>@product.Price</td>
                <td align="center">
                    <a href="@Url.Action("Buy","Cart",new{id=product.Id})"> Buy Now</a>

                </td>

            </tr>


        }

    </table>
   
</body>
        
</html>

ShoppingChart1/ShoppingChart1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>